### ISSUE TITLE
Add an explanation regarding running my testcafe test 

### ISSUE THREAD

**Issue by talamirredislabs** [danitseitlin/reportportal-testcafe-plugin#46]
1. add an explanation regarding the need to run testcafe test through mocha
2. how to insert all my args (rprotocol,rdomain...) to an configuration file
thanx :)

**Comment by danitseitlin** [comment]
@talamirredislabs Will this be good: https://github.com/danitseitlin/reportportal-testcafe-plugin/blob/master/CONTRIBUTING.md?

**Comment by danitseitlin** [comment]
Done in the link above, let me know if still missing.
