### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Linoyperetz** [danitseitlin/reportportal-testcafe-plugin#9]
`1) Unhandled promise rejection:
         TypeError: this.client.handleError is not a function
         at process.logs.forEach
      (/node_modules/testcafe-reporter-reportportal-plugin/lib/index.js:133:23)
         at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by danitseitlin** [comment]
@Linoyperetz The issue should be solved in the upcoming version @0.1.5 . Please update here if not.
